In [35]:
import pandas as pd
import requests
import re
import time

from bs4 import BeautifulSoup
from urllib.parse import quote_plus, urljoin
from pathlib import Path

In [36]:
df = pd.read_excel(r"D:\Proyek FEB\Publikasi internasional.xlsx")
df.head()

,No,Title,Authors,Journal,SCOPUS Q,Tahun,Volume / Issue,LINK DOI/ARTIKEL,SCOPUS SITASI
0,1,Ethnic identity and internal migration decisio...,ILMIAWAN AUWALIN,Journal of Ethnic and Migration Studies,?,2019-01-11 00:00:00,"Vol. 14, Issue 13",10.1080/1369183X.2018.1561252,?
1,2,The role of service quality within Indonesian ...,BADRI MUNIR SUKOCO,Journal of Islamic Marketing,?,2020-01-14 00:00:00,"Vol. 11, Issue 1",10.1108/JIMA-03-2017-0033,?
2,3,Developing Islamic crowdfunding website platfo...,MUHAMAD NAFIK HADI RYANDONO,Journal of Islamic Marketing,?,2020-08-21 00:00:00,"Vol. 11, Issue 5",10.1108/JIMA-02-2019-0022,?
3,4,Developing Islamic crowdfunding website platfo...,ACHSANIA HENDRATMI,Journal of Islamic Marketing,?,2020-08-21 00:00:00,"Vol. 11, Issue 5",10.1108/JIMA-02-2019-0022,?
4,5,Developing Islamic crowdfunding website platfo...,PUJI SUCIA SUKMANINGRUM,Journal of Islamic Marketing,?,2020-08-21 00:00:00,"Vol. 11, Issue 5",10.1108/JIMA-02-2019-0022,?

In [37]:
def normalize_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text).lower().strip()
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"[^a-z0-9\s]", "", text)
    return text.strip()

In [38]:
def parse_citation(text):
    if not text:
        return None
    
    match = re.search(r"(\d+)\s+cited", text, flags=re.IGNORECASE)
    
    if match:
        return int(match.group(1))
    
    return None

In [39]:
def parse_quartile(text):
    if not text:
        return None
    
    match = re.search(r"\b(Q[1-4])\b", text, flags=re.IGNORECASE)
    
    if match:
        return match.group(1).upper()
    
    if re.search(r"\bno-?Q\b", text, flags=re.IGNORECASE):
        return "no-Q"
    
    return None

In [40]:
def is_link_filled(value):
    if pd.isna(value):
        return False
    
    value = str(value).strip()
    
    if value == "" or value.lower() in ["nan", "none", "-", "?"]:
        return False
    
    return True

In [41]:
def normalize_doi_or_link(value):
    if not value:
        return None
    
    value = str(value).strip()
    
    if value == "" or value.lower() in ["nan", "none", "-", "?"]:
        return None
    
    # Sudah URL
    if value.startswith("http://") or value.startswith("https://"):
        return value
    
    # DOI mentah
    if value.startswith("10."):
        return f"https://doi.org/{value}"
    
    return value

In [42]:
def extract_doi_from_soup(soup):
    if soup is None:
        return None
    
    # 1. Coba ambil dari data-testid publication-doi
    doi_el = soup.select_one('[data-testid="publication-doi"]')
    if doi_el:
        doi_text = doi_el.get_text(" ", strip=True)
        doi_text = doi_text.replace("DOI:", "").strip()
        if doi_text.startswith("10."):
            return doi_text
    
    # 2. Coba cari pola DOI di seluruh teks halaman
    text = soup.get_text(" ", strip=True)
    
    match = re.search(r"\b10\.\d{4,9}/[-._;()/:A-Z0-9]+\b", text, flags=re.IGNORECASE)
    
    if match:
        return match.group(0).strip()
    
    return None

In [43]:
def fetch_page(url, sleep_time=1.0):
    headers = {
        "User-Agent": "Mozilla/5.0"
    }
    
    try:
        response = requests.get(url, headers=headers, timeout=30)
        time.sleep(sleep_time)
        
        if response.status_code != 200:
            return None, response.status_code
        
        soup = BeautifulSoup(response.text, "html.parser")
        return soup, response.status_code
    
    except Exception:
        return None, None

In [44]:
def get_sinta_first_result(title, current_link=None, sleep_time=1.5):
    base_url = "https://sinta.kemdiktisaintek.go.id/scopus/"
    search_url = f"{base_url}?q={quote_plus(str(title))}"
    
    headers = {
        "User-Agent": "Mozilla/5.0"
    }
    
    try:
        response = requests.get(search_url, headers=headers, timeout=30)
        time.sleep(sleep_time)
        
        if response.status_code != 200:
            return {
                "title": title,
                "matched_title": None,
                "scopus_q": None,
                "scopus_citation": None,
                "final_link": current_link if is_link_filled(current_link) else None,
                "detail_or_scopus_url": None,
                "status": "request_failed",
                "http_status": response.status_code,
                "source_url": search_url
            }
        
        soup = BeautifulSoup(response.text, "html.parser")
        
        # Ambil hasil pertama
        first_item = soup.select_one("div.ar-list-item")
        
        if first_item is None:
            return {
                "title": title,
                "matched_title": None,
                "scopus_q": None,
                "scopus_citation": None,
                "final_link": current_link if is_link_filled(current_link) else None,
                "detail_or_scopus_url": None,
                "status": "not_found",
                "http_status": response.status_code,
                "source_url": search_url
            }
        
        # Ambil elemen-elemen utama
        title_link_el = first_item.select_one(".ar-title a")
        title_el = first_item.select_one(".ar-title")
        cited_el = first_item.select_one(".ar-cited")
        quartile_el = first_item.select_one(".ar-quartile")
        year_el = first_item.select_one(".ar-year")
        
        matched_title = title_el.get_text(" ", strip=True) if title_el else None
        
        citation_text = cited_el.get_text(" ", strip=True) if cited_el else None
        quartile_text = quartile_el.get_text(" ", strip=True) if quartile_el else None
        year_text = year_el.get_text(" ", strip=True) if year_el else None
        
        scopus_citation = parse_citation(citation_text)
        scopus_q = parse_quartile(quartile_text)
        
        detail_or_scopus_url = None
        
        if title_link_el and title_link_el.get("href"):
            detail_or_scopus_url = urljoin(search_url, title_link_el.get("href"))
        
        # Logika link DOI/artikel
        if is_link_filled(current_link):
            final_link = normalize_doi_or_link(current_link)
            link_status = "existing_link_kept"
        else:
            final_link = None
            link_status = "link_missing"
            
            # Jika link judul langsung ke Scopus, simpan dulu sebagai fallback
            if detail_or_scopus_url:
                final_link = detail_or_scopus_url
                link_status = "article_link_from_sinta_result"
            
            # Kalau link detail bukan Scopus atau masih bisa dibuka, coba cari DOI di halaman tersebut
            if detail_or_scopus_url and "scopus.com" not in detail_or_scopus_url:
                detail_soup, detail_status = fetch_page(detail_or_scopus_url, sleep_time=1.0)
                doi = extract_doi_from_soup(detail_soup)
                
                if doi:
                    final_link = normalize_doi_or_link(doi)
                    link_status = "doi_found_from_detail"
        
        return {
            "title": title,
            "matched_title": matched_title,
            "sinta_year": year_text,
            "scopus_q": scopus_q,
            "quartile_text": quartile_text,
            "scopus_citation": scopus_citation,
            "citation_text": citation_text,
            "final_link": final_link,
            "detail_or_scopus_url": detail_or_scopus_url,
            "status": "found",
            "link_status": link_status,
            "http_status": response.status_code,
            "source_url": search_url
        }
    
    except Exception as e:
        return {
            "title": title,
            "matched_title": None,
            "scopus_q": None,
            "scopus_citation": None,
            "final_link": current_link if is_link_filled(current_link) else None,
            "detail_or_scopus_url": None,
            "status": "error",
            "error": str(e),
            "source_url": search_url
        }

# testing

In [45]:
sample_title = "Ethnic identity and internal migration decision in Indonesia"

result = get_sinta_first_result(sample_title)

result

{'title': 'Ethnic identity and internal migration decision in Indonesia',
 'matched_title': 'Ethnic identity and internal migration decision in Indonesia',
 'sinta_year': '2020',
 'scopus_q': 'Q1',
 'quartile_text': 'Q1 Journal',
 'scopus_citation': 24,
 'citation_text': '24 cited',
 'final_link': 'https://www.scopus.com/record/display.uri?eid=2-s2.0-85060010639&origin=resultslist',
 'detail_or_scopus_url': 'https://www.scopus.com/record/display.uri?eid=2-s2.0-85060010639&origin=resultslist',
 'status': 'found',
 'link_status': 'article_link_from_sinta_result',
 'http_status': 200,
 'source_url': 'https://sinta.kemdiktisaintek.go.id/scopus/?q=Ethnic+identity+and+internal+migration+decision+in+Indonesia'}

In [46]:
print("Title:", result["title"])
print("Matched:", result["matched_title"])
print("Q:", result["scopus_q"])
print("Citation:", result["scopus_citation"])
print("Final link:", result["final_link"])
print("Detail/Scopus URL:", result["detail_or_scopus_url"])
print("Status:", result["status"])

Title: Ethnic identity and internal migration decision in Indonesia
Matched: Ethnic identity and internal migration decision in Indonesia
Q: Q1
Citation: 24
Final link: https://www.scopus.com/record/display.uri?eid=2-s2.0-85060010639&origin=resultslist
Detail/Scopus URL: https://www.scopus.com/record/display.uri?eid=2-s2.0-85060010639&origin=resultslist
Status: found

In [47]:
df["title_normalized"] = df["Title"].apply(normalize_text)

unique_articles = (
    df[["Title", "title_normalized", "LINK DOI/ARTIKEL"]]
    .dropna(subset=["Title"])
    .drop_duplicates(subset=["title_normalized"])
    .reset_index(drop=True)
)

len(unique_articles)

1332

In [48]:
results = []

for i, row in unique_articles.iterrows():
    title = row["Title"]
    current_link = row["LINK DOI/ARTIKEL"]
    
    print(f"{i+1}/{len(unique_articles)} - {title[:90]}")
    
    result = get_sinta_first_result(
        title=title,
        current_link=current_link,
        sleep_time=1.5
    )
    
    results.append(result)

sinta_results_df = pd.DataFrame(results)

1/1332 - Ethnic identity and internal migration decision in Indonesia
2/1332 - The role of service quality within Indonesian customers satisfaction and loyalty and its i
3/1332 - Developing Islamic crowdfunding website platform for startup companies in Indonesia
4/1332 - Exploration of pilgrimage tourism in Indonesia
5/1332 - A critical assessment of retail sovereign sukuk in Indonesia
6/1332 - The impact of auditors’ awareness of the profession’s reputation for independence on audit
7/1332 - Exploring the role of visual aesthetics and presentation modality in luxury fashion brand
8/1332 - Anger punishes, compassion forgives: How discrete emotions mitigate double standards in co
9/1332 - Managing paradoxes of innovation in an Indonesian TV group
10/1332 - Competitiveness and cost behaviour: evidence from the retail industry
11/1332 - Effects of Halal social media and customer engagement on brand satisfaction of Muslim cust
12/1332 - Islamic microfinance institution: Survey data from Indonesia
13/1332 - Explaining regional inflation programmes in Indonesia: Does inflation rate converge?
14/1332 - The impact of exchange rate volatility on Indonesia's top exports to the five main export
15/1332 - Analysis of twin deficits hypothesis in Indonesia and its impact on financial crisis
16/1332 - Earnings management, business strategy, and bankruptcy risk: evidence from Indonesia
17/1332 - Characteristics of auditors’ non-audit services and accruals quality in Malaysia
18/1332 - Board meeting, loss, and corporate social responsibility disclosure
19/1332 - Family firms, political connections, and managerial short-termism
20/1332 - Are emotions exacerbating the recency bias?: An experimental study
21/1332 - Settlement of foreign labour market policy in ASEAN + 3 free trade perspectives in Indones
22/1332 - A review of social franchising: Consolidation of literature and future research direction
23/1332 - Remuneration committees, executive remuneration, and firm performance in Indonesia
24/1332 - Indonesian peer to peer lending (P2P) at entrant’s disruptive trajectory
25/1332 - The effect of leadership behaviour on knowledge management practices at the PT Power Plant
26/1332 - The preference and prospects of sugar needs in micro, small and medium enterprise industri
27/1332 - A study of recent migrants in both the formal and informal sectors: Evidence from Sakernas
28/1332 - Vessel automatic operational identification system (AOIS): A proposed system to prevent il
29/1332 - The role of a compost house in producing externalities, based on an Islamic perspective
30/1332 - The effect of financial reporting and debt maturity quality of investment efficiency with
31/1332 - Negative emotions in excessive product packaging: The effect of environmental concerns
32/1332 - Duration model for maturity gap risk management in Islamic banks
33/1332 - The effects of pension plans on audit pricing: Evidence from Indonesia
34/1332 - Empowerment of waste bank in Islam: Case study of Bank Sampah Induk Surabaya (BSIS)
35/1332 - The effect of ownership structure and intellectual capital on firm value with firm perform
36/1332 - Interpersonal relationship of salesperson to customer trust on islamic insurance in Suraba
37/1332 - Customer satisfaction between perceptions of environment destination brand and behavioural
38/1332 - Bank financial soundness and the disclosure of banking sustainability reporting in Indones
39/1332 - The role of a sustainability report in mediating the effect of board size on firm value
40/1332 - Level of student awareness in using tumbler water bottles in an effort to reduce the use o
41/1332 - The effect of environmental disclosures on ISSI company stock prices
42/1332 - The challenge and the impact of green belt as an air pollution control
43/1332 - Effect of Corporate Social Responsibility (CSR) disclosure to earnings management with eff
44/1332 - Trade and food security: Case for Indonesian fishery export
45/1332 - The impact of sectoral financing to NPF of BPRS in Indonesia from January 2012-August 2018
46/1332 - The impact of mangrove ecotourism on welfare from the perspective of Maqasid al-Sharia
47/1332 - The role of supply chain management on consumer service innovativeness and consumer attitu
48/1332 - Asymmetric impact of textile and clothing manufacturing on carbon-dioxide emissions: Evide
49/1332 - The effect of kersen (Muntingia calabura L) leaf extract on bacteria Aeromonas salmonicida
50/1332 - Disclosure of sustainability report mediating good corporate governance mechanism on stock
51/1332 - Sustainability report practices in Indonesia: Context, policy, and readability
52/1332 - Are independent commissioners able to mitigate higher audit fees in politically connected
53/1332 - Political connections, corporate governance, and the cost of equity in Malaysia
54/1332 - Ensuring competitive and alliance formation intensity for continuous improvement in manufa
55/1332 - Identification of prominent sectors in the regency of Nganjuk before and after the era of
56/1332 - The effect of job resources as the intervening variable towards turnover intention and emp
57/1332 - Seven efficiency analysis based on the BCC method on Sharia equity mutual funds
58/1332 - Influence of picture health warnings on the attitudes and intention to quit smoking in mid
59/1332 - Effects of foreign direct investment (FDI), trade openness, exchange rate and inflation on
60/1332 - The seriousness in applying accounting standards and the cost of capital
61/1332 - The effect of diversification and executive compensation on firm value: Study of manufactu
62/1332 - Gender inequality and women poverty in Indonesia
63/1332 - The effect of participation on user satisfaction in the development of information systems
64/1332 - The effect of cultural dimensions on earnings management practices in some ASEAN countries
65/1332 - Identification of information distortion on data flow diagram (DFD) and corrective plans u
66/1332 - The positive accounting theory, corporate governance, and income smoothing
67/1332 - Operating cash flow, profitability, liquidity, leverage and dividend policy
68/1332 - Analysis of the effect of non-cash payments on cash distribution in Indonesia, period 2010
69/1332 - The impacts of good corporate governance on corporate performance with corporate social re
70/1332 - The effect of macroeconomic factors and market share on the sharia banking industry in Ind
71/1332 - Identification of real estate bubbles in Indonesia
72/1332 - The impact of financial structure, inflation, and economical growth on non-performing fina
73/1332 - Transparency in the central bank and the mechanism of transmission of interest rates: Case
74/1332 - The decision-making process of IMC activities in the sponsorship bidding of bank Jatim for
75/1332 - The factors affecting fraudulent financial reporting in the fraud triangle perspective
76/1332 - External assurance on sustainability report disclosure and firm value: Evidence from Indon
77/1332 - Lean hospital management implementation in health care service: A multicase study
78/1332 - Determinants of innovation capability in the islamic banking
79/1332 - Foreign exchange intervention: Has it been effective in Indonesia?
80/1332 - Foreign ownership reactions to the adoption of international financial reporting standards
81/1332 - Implementation of Islamic entrepreneurial culture in Islamic boarding schools
82/1332 - A comparative analysis of the productivity of Islamic banking in Indonesia, Malaysia and B
83/1332 - The 'holier-than-thou' perception bias of business workers and business students in Indone
84/1332 - An integrated model of the adoption of information technology in travel service
85/1332 - An effort to mitigate deviant behaviour in the workplace: Does justice matter?
86/1332 - Using hegel's dialectic pattern to review the adoption of the IFRS in Indonesia
87/1332 - Self control, perceived opportunity, knowledge and attitude as predictors of plagiarism by
88/1332 - Performance-based budgeting and its impact on control effectiveness: A case study of the s
89/1332 - Perceptions of the 7p marketing mix of Islamic banks in Indonesia: What do twitter users s
90/1332 - Halal supply chain management practice model: A case study in evidence of halal supply cha
91/1332 - Governance in a village fund program in East Java Indonesia
92/1332 - Critical assessment of higher education for sustainable development: Evidence in Indonesia
93/1332 - Inversed illiquidity and corporate investment on the Indonesian stock exchange's Kompas 10
94/1332 - Why is workplace spirituality important for auditors?
95/1332 - The relationship between performance, innovation, earnings management and firm value: An I
96/1332 - The mediating role of green innovation on the effect of environment-based culture on compa
97/1332 - An experimental study of the effect of financial and non-financial information on intentio
98/1332 - Effect of price and non-price initiatives promotion towards healthy food selection
99/1332 - Electronic village financial system implementation in Banyuwangi: Ready or not?
100/1332 - Workplace spirituality and job satisfaction toward job performance: The mediation role of
101/1332 - Building nurses' organizational commitment by providing good quality of work life
102/1332 - How does the presidential election period affect the performance of the state-owned enterp
103/1332 - The antecedents of salesperson deviant behavior: The role of work meaningfulness
104/1332 - Sentiment analysis trend on sustainability reporting in Indonesia: Evidence from construct
105/1332 - Determinants of tourism demand in Indonesia: A panel data analysis
106/1332 - Assessment of criteria for performance excellence (KPKU) and firm performance: Evidence fr
107/1332 - Internal audit functions and audit outcomes: Evidence from Indonesia
108/1332 - Data set on coping strategies in the digital age: The role of psychological well-being and
109/1332 - Discomfort and organizational change as a part of becoming a world-class university
110/1332 - The influence of internal auditor towards fraud on mining companies: Indonesia stock excha
111/1332 - Ceo & cfo education and r&d investment in indonesia
112/1332 - Innovation of vertical intra-industry trade: Asean-5 and China electronic and telematic se
113/1332 - Leadership perspective between leaders and subordinates in a marketing communication agent
114/1332 - A conceptual framework for relationship between symbolic risk consumption with electronic
115/1332 - Zakat institutions’ mustahiq transformation in developing countries: Comparison study
116/1332 - Managerial ownership, firm size, financial performance, and corporate environmental disclo
117/1332 - The effect of cash turnover and receivable turnover on profitability
118/1332 - Strategic management accounting and university performance: A critical review
119/1332 - Budgetary participation effect, budget emphasis, and information asymmetry on budgetary sl
120/1332 - Does the Asean-Japan comprehensive economic partnership cause trade creation and trade div
121/1332 - Determinants of social media use by handicraft industry of Indonesia and its impact on exp
122/1332 - The Moderating Effects of Gender between Patient Intimacy, Trust, and Loyalty
123/1332 - Comparison of the Islamic and the conventional stock market in Indonesia and developed cou
124/1332 - Firm size, firm age and the readability of the MD&A report
125/1332 - Depiction of connection between library and information science in articles published by u
126/1332 - The influence of corporate social responsibility (CSR) disclosure on firm values with stak
127/1332 - Investor experience and expectation towards decision-making process
128/1332 - Research and development intensity, firm performance, and green product innovation
129/1332 - Consumer benefits received in the instagram account on brand trust and commitment
130/1332 - Indonesian stock market: Do bear and bull matter?
131/1332 - The urbanization pattern, economic growth, co2 gas emissions and land transportation inten
132/1332 - Efficiency of national zakat institutions on increasing muzakki from 2015-2016
133/1332 - Increasing number of young unemployment due to inflation, education, and economic growth
134/1332 - Taylor rule’s accuracy in determining the countries short-term nominal interest rate
135/1332 - Company's financial performance before and after registering on indonesia sharia stock ind
136/1332 - Correlation of actor bonds, activity links, and resources ties on enterprizes competitiven
137/1332 - The effect of organizational commitment towards employees’ islamic performance
138/1332 - The impact of monopoly power, and asymmetric information to adopt e-procurement
139/1332 - Does the spin-off policy change the shariah bank financial ratio?
140/1332 - Effect of innovation on company performance with environmental performance as a mediating
141/1332 - The role of social capital in improving community welfare in East Java, Indonesia
142/1332 - The infrastructure investment effect and transportation sector toward economic growth in I
143/1332 - Facts behind the behavioral intention to use the go-jek application
144/1332 - The relation of business complexity to audit fee on non-financial company
145/1332 - The impact of rupiah/usd exchange, on the indonesian manufacturing sectors in 2005-2016
146/1332 - Good corporate governance as moderator of the diversification of portfolios
147/1332 - Impact of distance, exchange rate, population, and gdp on natural rubber export
148/1332 - The impact of audit paradigm and obedience pressure on perceived audit judgment
149/1332 - Identification of non-sharia compliant activity in conventional insurance
150/1332 - Military reform, militarily-connected firms and auditor choice
151/1332 - Risk taking investment as the interaction effect of loss aversion and information (Pilot t
152/1332 - The impact of corporate governance in forming a strong supply chain: Evidence from Indones
153/1332 - The supply chain quality management in high education: A case study in Indonesia
154/1332 - The local economy and Re-election of incumbent district leaders in Indonesia
155/1332 - The effect of board effectiveness and independence on the narration of greenhouse gases (g
156/1332 - The effect of ownership concentration, ownership insider, and family ownership on human re
157/1332 - The effect of earning per share, debt to equity ratio and return on assets on stock prices
158/1332 - Mediating effect of strategy on competitive pressure, stakeholder pressure and strategic p
159/1332 - Innovation, environmental management accounting, future performance: Evidence in Indonesia
160/1332 - Effects of light, sucrose concentration and repetitive subculture on callus growth and med
161/1332 - Contingency model to increase the uptake of higher education graduates in the job market
162/1332 - The impact of Eco-efficiency on firm value and firm size: An Indonesian study
163/1332 - The relationship between corporate social responsibility and tax aggressiveness: An Indone
164/1332 - Corporate social responsibility, foreign ownership, and firm financial performance
165/1332 - Controlling shareholders' tendency toward tax avoidance in family firms and independent co
166/1332 - The effect of share ownership structure, board of commissioner size, and audit committee s
167/1332 - Technology and stress: A proposed framework for coping with stress in indonesian higher ed
168/1332 - Political connection, executive compensation and profit management in Indonesia.
169/1332 - Determinants on the extent of enterprise risk management (ERM) disclosure in annual report
170/1332 - Market reaction to a firm environmental performance assessment program (PROPER) rank: An I
171/1332 - Board diversity and corporate social responsibility disclosure in the property, real estat
172/1332 - Firm performance in environmentally-friendly firms in Indonesia: The effects of green inno
173/1332 - Budgetary slack and use in Indonesia: 'Participation on budget' and 'budget emphasis' as m
174/1332 - The effect of environmental management practice on firm performance: An Indonesian study.
175/1332 - Cross-listing and corporate social responsibility: Evidence from manufacturing companies i
176/1332 - CEO over-confidence and tax avoidance
177/1332 - Determinant intellectual capital disclosure factors in integrated reporting
178/1332 - Environmental innovation as mediation: Knowledge management and firm performance
179/1332 - Measures that matter: an empirical investigation of intellectual capital and financial per
180/1332 - An analysis of the relationship between tax avoidance and debt maturity with financial con
181/1332 - Cash flow, investment, and internationalisation strategy
182/1332 - Independent director, independent commissioner, product market competition, and firm perfo
183/1332 - Cash flow analysis, corporate governance and financial distress
184/1332 - Servant leadership and religiosity: An indicator of employee performance in the education
185/1332 - The relationship between business and the audit fee: Evidence from Indonesian listed compa
186/1332 - Do foreign investments and renewable energy consumption affect the air quality? Case study
187/1332 - Does biodiesel initiative save the state budget?
188/1332 - Authenticity as a corporate social responsibility platform for building customer loyalty
189/1332 - Political connections, overinvestment and governance mechanism in Indonesia
190/1332 - Motivation, leadership, supply chain management toward employee green behavior with organi
191/1332 - Workload stress and conservatism: An audit perspective
192/1332 - Insights into research on carbon disclosure
193/1332 - Implementation of integrated reporting: A cross-countries’ study
194/1332 - Financial performance of rural banks in Indonesia: A two-stage DEA approach
195/1332 - A quest to minimize cost of debt by utilizing human resources disclosure
196/1332 - Human resource disclosures as management strategy to enhance its competitive success
197/1332 - Operational performance of sme: The impact of entrepreneurial leadership, good governance
198/1332 - The influence of corporate governance on sustainability report management: The moderating
199/1332 - The effect of internal banking and macroeconomic variables on systemic risk
200/1332 - The pseudo-culture: Financial management risk in village government
201/1332 - People equity model as an effort to increase employees’ intention to stay
202/1332 - Breadth and depth outreach of Islamic cooperatives: do size, non-performing finance, and g
203/1332 - The impact of public ownership and share warrants on market performance of IPOs: Evidence
204/1332 - Mediating effect of business process performance on innovation strategy-cost performance r
205/1332 - Analysis of determinants of Indonesian agricultural exports
206/1332 - Managing the firm environmental and financial performance: New insight from government own
207/1332 - The effect of FDI, labor and wage on regional economic development: A case study
208/1332 - Impact of intellectual capital on firm value through corporate reputation as a mediating v
209/1332 - Knowledge sharing behavior between self-leadership and innovative behavior
210/1332 - Text mining on sustainability reporting: A case study
211/1332 - Impact of disruption era on organization performance sustainability: A case study
212/1332 - The gade clean and the gold waste bank: Society's economic empowerment based on environmen
213/1332 - Towards sustainability of companies' development via attracting millennial job applicants:
214/1332 - Developing green operations to minimize energy consumption by pdca cycle of ISO 50001. A c
215/1332 - Does competition and foreign investment spur industrial efficiency?: firm-level evidence f

In [51]:
df1=pd.DataFrame(results)
df1

,title,matched_title,sinta_year,scopus_q,quartile_text,scopus_citation,citation_text,final_link,detail_or_scopus_url,status,link_status,http_status,source_url,error
0,Ethnic identity and internal migration decisio...,Ethnic identity and internal migration decisio...,2020,Q1,Q1 Journal,24.0,24 cited,https://doi.org/10.1080/1369183X.2018.1561252,https://www.scopus.com/record/display.uri?eid=...,found,existing_link_kept,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN
1,The role of service quality within Indonesian ...,The role of service quality within Indonesian ...,2020,Q2,Q2 Journal,60.0,60 cited,https://doi.org/10.1108/JIMA-03-2017-0033,https://www.scopus.com/record/display.uri?eid=...,found,existing_link_kept,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN
2,Developing Islamic crowdfunding website platfo...,Developing Islamic crowdfunding website platfo...,2020,Q2,Q2 Journal,48.0,48 cited,https://doi.org/10.1108/JIMA-02-2019-0022,https://www.scopus.com/record/display.uri?eid=...,found,existing_link_kept,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN
3,Exploration of pilgrimage tourism in Indonesia,Exploration of pilgrimage tourism in Indonesia,2020,Q2,Q2 Journal,33.0,33 cited,https://doi.org/10.1108/JIMA-10-2018-0188,https://www.scopus.com/record/display.uri?eid=...,found,existing_link_kept,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN
4,A critical assessment of retail sovereign suku...,A critical assessment of retail sovereign suku...,2020,Q2,Q2 Journal,9.0,9 cited,https://doi.org/10.1108/QRFM-10-2018-0109,https://www.scopus.com/record/display.uri?eid=...,found,existing_link_kept,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,Does economic uncertainty hinder or help busin...,None,NaN,None,NaN,NaN,NaN,10.1108/IMEFM-05-2024-0238,None,not_found,NaN,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN
1328,Assessing the impact of economic uncertainty o...,None,NaN,None,NaN,NaN,NaN,10.1108/JIABR-05-2024-0175,None,not_found,NaN,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN
1329,Do high-pollution firm need more environmental...,None,NaN,None,NaN,NaN,NaN,10.1108/SRJ-01-2025-0015,None,not_found,NaN,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN
1330,"The impact of digitalization, education, and i...",None,NaN,None,NaN,NaN,NaN,10.1016/j.ssaho.2025.101423,None,not_found,NaN,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN
1331,From Crisis to Recovery: Understanding the Imp...,None,NaN,None,NaN,NaN,NaN,10.25133/JPSSv342026.004,None,not_found,NaN,200.0,https://sinta.kemdiktisaintek.go.id/scopus/?q=...,NaN

In [52]:
df1.to_excel(r"D:\Proyek FEB\lengkapin data\sinta_results.xlsx", index=False)